"""Added new fields to User model

Revision ID: 81c4537f5623
Revises: 
Create Date: 2025-07-18 19:18:42.928285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81c4537f5623'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=False, server_default='0'))

        batch_op.add_column(sa.Column('payment_id', sa.String(length=100), nullable=False, server_default=''))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('payment_id')
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
