"""Initial migration

Revision ID: a80f32809141
Revises: 
Create Date: 2025-07-16 16:07:43.149372

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a80f32809141'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('total_price')

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('availability', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('rooms_name_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('rooms_created_by_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('created_by')
        batch_op.drop_column('capacity')
        batch_op.drop_column('available')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('available', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('rooms_created_by_fkey'), 'users', ['created_by'], ['id'])
        batch_op.create_unique_constraint(batch_op.f('rooms_name_key'), ['name'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('user_id')
        batch_op.drop_column('availability')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
